### ISSUE TITLE
Get @jbuckle app front-end image sizes (thumbnails)

### ISSUE THREAD

**Issue by bassettsj** [NEU-Libraries/cerberus#185]
``` css
.thumbnail-s1{
 width: 85px;
 height: 85px;
}

.thumbnail-s1-2x,
.thumbnail-s2{
 width: 170px;
 height: 170px;
}

.thumbnail-span2-2x{
 height: 340px;
 width: 340px;
}

.thumbnail-s4{
 height: auto;
 width: 340px;
}

.thumbnail-s4-2x{
 height: auto;
 width: 680px;
}


.thumbnail-s10{
 width: 970px;
 height: auto;
}

.thumbnail-s10-2x{
 width: 1940px;
 height: auto;
}

```
